In [ ]:
# Netflix Data Cleaning Task
#The objective of this task is to clean and preprocess the Netflix dataset using Python and Pandas.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('Netflix_Raw_Dataset.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#shape of the dataset

In [2]:
df.shape

(8807, 12)

In [ ]:
#finding the null values

In [3]:
df.isnull()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,True,True,True,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,False,False,False,False,False,False,False,False,False,False,False,False
8803,False,False,False,True,True,True,False,False,False,False,False,False
8804,False,False,False,False,False,False,False,False,False,False,False,False
8805,False,False,False,False,False,False,False,False,False,False,False,False
8806,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#sum of the null values

In [4]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
#Removed duplicates

In [6]:
df = df.dropna()

In [7]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#drop duplicates

In [9]:
df = df.drop_duplicates()

In [ ]:
#Standardize text values like gender, country names, etc.

In [11]:
text_cols = ['type', 'title', 'director', 'cast', 
             'country', 'rating', 'listed_in']

for col in text_cols:
    df[col] = df[col].str.lower().str.strip()

In [12]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,movie,sankofa,haile gerima,"kofi ghanaba, oyafunmike ogunlano, alexandra d...","united states, ghana, burkina faso, united kin...","September 24, 2021",1993,tv-ma,125 min,"dramas, independent movies, international movies","On a photo shoot in Ghana, an American model s..."
8,s9,tv show,the great british baking show,andy devonshire,"mel giedroyc, sue perkins, mary berry, paul ho...",united kingdom,"September 24, 2021",2021,tv-14,9 Seasons,"british tv shows, reality tv",A talented batch of amateur bakers face off in...
9,s10,movie,the starling,theodore melfi,"melissa mccarthy, chris o'dowd, kevin kline, t...",united states,"September 24, 2021",2021,pg-13,104 min,"comedies, dramas",A woman adjusting to life after a loss contend...
12,s13,movie,je suis karl,christian schwochow,"luna wedler, jannis niewöhner, milan peschel, ...","germany, czech republic","September 23, 2021",2021,tv-ma,127 min,"dramas, international movies",After most of her family is murdered in a terr...
24,s25,movie,jeans,s. shankar,"prashanth, aishwarya rai bachchan, sri lakshmi...",india,"September 21, 2021",1998,tv-14,166 min,"comedies, international movies, romantic movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,movie,zinzana,majid al ansari,"ali suliman, saleh bakri, yasa, ali al-jabri, ...","united arab emirates, jordan","March 9, 2016",2015,tv-ma,96 min,"dramas, international movies, thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,"November 20, 2019",2007,r,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,"November 1, 2019",2009,r,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...
8805,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,"January 11, 2020",2006,pg,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero..."
8806,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,"March 2, 2019",2015,tv-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#Convert date formats to a consistent type (e.g., dd-mm-yyyy)

In [13]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df['date_added_formatted'] = df['date_added'].dt.strftime('%d-%m-%Y')

In [14]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,date_added_formatted
7,s8,movie,sankofa,haile gerima,"kofi ghanaba, oyafunmike ogunlano, alexandra d...","united states, ghana, burkina faso, united kin...",2021-09-24,1993,tv-ma,125 min,"dramas, independent movies, international movies","On a photo shoot in Ghana, an American model s...",24-09-2021
8,s9,tv show,the great british baking show,andy devonshire,"mel giedroyc, sue perkins, mary berry, paul ho...",united kingdom,2021-09-24,2021,tv-14,9 Seasons,"british tv shows, reality tv",A talented batch of amateur bakers face off in...,24-09-2021
9,s10,movie,the starling,theodore melfi,"melissa mccarthy, chris o'dowd, kevin kline, t...",united states,2021-09-24,2021,pg-13,104 min,"comedies, dramas",A woman adjusting to life after a loss contend...,24-09-2021
12,s13,movie,je suis karl,christian schwochow,"luna wedler, jannis niewöhner, milan peschel, ...","germany, czech republic",2021-09-23,2021,tv-ma,127 min,"dramas, international movies",After most of her family is murdered in a terr...,23-09-2021
24,s25,movie,jeans,s. shankar,"prashanth, aishwarya rai bachchan, sri lakshmi...",india,2021-09-21,1998,tv-14,166 min,"comedies, international movies, romantic movies",When the father of the man she loves insists t...,21-09-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,movie,zinzana,majid al ansari,"ali suliman, saleh bakri, yasa, ali al-jabri, ...","united arab emirates, jordan",2016-03-09,2015,tv-ma,96 min,"dramas, international movies, thrillers",Recovering alcoholic Talal wakes up inside a s...,09-03-2016
8802,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a...",20-11-2019
8804,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...,01-11-2019
8805,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero...",11-01-2020
8806,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...,02-03-2019

In [ ]:
#Rename column headers to be clean and uniform (e.g., lowercase, no spaces)

In [15]:
df.columns = df.columns.str.lower()

In [16]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,date_added_formatted
7,s8,movie,sankofa,haile gerima,"kofi ghanaba, oyafunmike ogunlano, alexandra d...","united states, ghana, burkina faso, united kin...",2021-09-24,1993,tv-ma,125 min,"dramas, independent movies, international movies","On a photo shoot in Ghana, an American model s...",24-09-2021
8,s9,tv show,the great british baking show,andy devonshire,"mel giedroyc, sue perkins, mary berry, paul ho...",united kingdom,2021-09-24,2021,tv-14,9 Seasons,"british tv shows, reality tv",A talented batch of amateur bakers face off in...,24-09-2021
9,s10,movie,the starling,theodore melfi,"melissa mccarthy, chris o'dowd, kevin kline, t...",united states,2021-09-24,2021,pg-13,104 min,"comedies, dramas",A woman adjusting to life after a loss contend...,24-09-2021
12,s13,movie,je suis karl,christian schwochow,"luna wedler, jannis niewöhner, milan peschel, ...","germany, czech republic",2021-09-23,2021,tv-ma,127 min,"dramas, international movies",After most of her family is murdered in a terr...,23-09-2021
24,s25,movie,jeans,s. shankar,"prashanth, aishwarya rai bachchan, sri lakshmi...",india,2021-09-21,1998,tv-14,166 min,"comedies, international movies, romantic movies",When the father of the man she loves insists t...,21-09-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,movie,zinzana,majid al ansari,"ali suliman, saleh bakri, yasa, ali al-jabri, ...","united arab emirates, jordan",2016-03-09,2015,tv-ma,96 min,"dramas, international movies, thrillers",Recovering alcoholic Talal wakes up inside a s...,09-03-2016
8802,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a...",20-11-2019
8804,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...,01-11-2019
8805,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero...",11-01-2020
8806,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...,02-03-2019

In [ ]:
#Check and fix data types (e.g., age should be int, date as datetime).

In [17]:
df.dtypes

show_id                         object
type                            object
title                           object
director                        object
cast                            object
country                         object
date_added              datetime64[ns]
release_year                     int64
rating                          object
duration                        object
listed_in                       object
description                     object
date_added_formatted            object
dtype: object

In [18]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,date_added_formatted
7,s8,movie,sankofa,haile gerima,"kofi ghanaba, oyafunmike ogunlano, alexandra d...","united states, ghana, burkina faso, united kin...",2021-09-24,1993,tv-ma,125 min,"dramas, independent movies, international movies","On a photo shoot in Ghana, an American model s...",24-09-2021
8,s9,tv show,the great british baking show,andy devonshire,"mel giedroyc, sue perkins, mary berry, paul ho...",united kingdom,2021-09-24,2021,tv-14,9 Seasons,"british tv shows, reality tv",A talented batch of amateur bakers face off in...,24-09-2021
9,s10,movie,the starling,theodore melfi,"melissa mccarthy, chris o'dowd, kevin kline, t...",united states,2021-09-24,2021,pg-13,104 min,"comedies, dramas",A woman adjusting to life after a loss contend...,24-09-2021
12,s13,movie,je suis karl,christian schwochow,"luna wedler, jannis niewöhner, milan peschel, ...","germany, czech republic",2021-09-23,2021,tv-ma,127 min,"dramas, international movies",After most of her family is murdered in a terr...,23-09-2021
24,s25,movie,jeans,s. shankar,"prashanth, aishwarya rai bachchan, sri lakshmi...",india,2021-09-21,1998,tv-14,166 min,"comedies, international movies, romantic movies",When the father of the man she loves insists t...,21-09-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,movie,zinzana,majid al ansari,"ali suliman, saleh bakri, yasa, ali al-jabri, ...","united arab emirates, jordan",2016-03-09,2015,tv-ma,96 min,"dramas, international movies, thrillers",Recovering alcoholic Talal wakes up inside a s...,09-03-2016
8802,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a...",20-11-2019
8804,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...,01-11-2019
8805,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero...",11-01-2020
8806,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...,02-03-2019